fastlane_version '2.176.0'

before_all do
  ensure_git_branch
 # ensure_git_status_clean
  git_pull
end

platform :ios do
   # iOS Lanes
#desc 'Fetch certificates and provisioning profiles'
#lane :certificates do
#  match(app_identifier: 'com.app.bundle', type: 'development', readonly: true)
#  match(app_identifier: 'com.app.bundle', type: 'appstore', readonly: true)
#end
desc 'Build the iOS application.'
private_lane :build do
#  certificates
  increment_build_number(xcodeproj: '/Users/Abin/Aswani/ASWANI_TEST/Aswani_Thanx/ios/AswaniThanx.xcodeproj')

#  gym(scheme: 'AswaniThanx', project: '/Users/Abin/Aswani/ASWANI_TEST/Aswani_Thanx/ios/AswaniThanx.xcodeproj', configuration: "Debug", skip_codesigning: true)
build_app(
  project: "/Users/Abin/Aswani/ASWANI_TEST/Aswani_Thanx/ios/AswaniThanx.xcodeproj",
  configuration: "Debug",
  scheme: "AswaniThanx",
  skip_codesigning: true,
  skip_archive: true)

end

desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: 'Bump build', xcodeproj: './ios/AswaniThanx.xcodeproj')
    push_to_git_remote
  end

lane :deployment do |version: version|
  setup_certificates
  bump_version_number(version: version)
  canary
  production
  sh 'npm run repositories:upload:ios'
  commit_and_push_version_bump
  git_flow_merge(version: version)
  slack_notification(platform: 'iOS', version: version)
end
end


#platform :android do
  # Android Lanes
#end
